---
- name: install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - curl
    - python-httplib2
    - python-pip
- name: install python tools with pip
  pip: name={{ item }} state=present   
  with_items: 
    - ansible-lint