---
- name: install tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-mysqldb
      
- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: ensure mysql is listening on all port
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address 
              line="bind-address = {{ facter_ipaddress_eth1 }}"
  notify: restart mysql

- name: ensure mysql service is running
  service: name=mysql state=started enabled=yes

- name: configure demo database
  mysql_db: name={{ db_name }} state=present

- name: create demo user
  mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_user_name }}.*:ALL 
              host='{{ db_user_host }}' state=present