---
- name: install tools
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-mysqldb
      
- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: ensure mysql is listening on all port
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address 
              line="bind-address = {{ ansible_eth0.ipv4.address }}"
  notify: restart mysql

- name: ensure mysql service is running
  service: name=mysql state=started enabled=yes

- name: configure demo database
  mysql_db: name=demo state=present

- name: create demo user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present